global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets:
        - 'fastapi:9108'
        - 'producers_flow_worker:9102'
        - 'producers_flow_worker:9103'
        - 'producers_flow_worker:9106'
        - 'storers_flow_worker:9104'
        - 'storers_flow_worker:9109'
        - 'storers_flow_worker:9110'
        - 'processors_flow_worker:9105'
        - 'anomaly_flow_worker:9107'
  - job_name: 'kafka'
    static_configs:
      - targets:
        - 'kafka:9101'