global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-jmx-exporter'
    static_configs:
      - targets: ['kafka:9101']
  - job_name: 'app-producer-consumer'
    static_configs:
      - targets: ['host.docker.internal:9102']