scrape_configs:
  - job_name: 'crypto-producer'
    static_configs:
      - targets: ['host.docker.internal:9101']

  - job_name: 'crypto-consumer'
    static_configs:
      - targets: ['host.docker.internal:9102']

  - job_name: 'news-ingest'
    static_configs:
      - targets: ['host.docker.internal:9103']

  - job_name: 'sentiment_analysis'
    static_configs:
      - targets: ['host.docker.internal:9104']

  - job_name: 'score-and-join'
    static_configs:
      - targets: ['host.docker.internal:9105']

  - job_name: 'ingest_onchain'
    static_configs:
      - targets: ['host.docker.internal:9106']

  - job_name: 'anomaly_detection'
    static_configs:
      - targets: ['host.docker.internal:9107']

  - job_name: 'onchain_consumer_to_db'
    static_configs:
      - targets: ['host.docker.internal:9108']

  - job_name: 'sentiment_to_db'
    static_configs:
      - targets: [host.docker.internal:9109']